import { getServicesQuery } from '@/app/services/getServicesQuery';
import PaslaugosPage from '@/components/pages/PaslaugosPage';
import axios from 'axios'
import { GetServerSideProps } from 'next'
import Head from 'next/head'

type Props = {
  services: any;
}
export default function Paslaugos({ services }: Props) {
  return (
    <>
      <Head>
        <title>Ortopedijos paslaugų klinika: Kontaktai</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PaslaugosPage services={services} />
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const data = await axios.get(getServicesQuery())

  return {
    props: {
      services: data.data,
    }
  }
}
