import { ReviewsResponseType } from '@/app/services/ReviewTypes'
import { Typography } from '@mui/material'
import Grid from '@mui/material/Grid'
import Stack from '@mui/system/Stack'
import React from 'react'
import Layout from '../Layout'
import { getColors } from '../layout/colors'

type Props = {
    reviews: ReviewsResponseType;
}
const PrivacyPolicyPagePage = ({ reviews }: Props) => {
    const colors = getColors()
    return (
        <Layout title={'Paslaugos'} color={"#1E6EA1"} reviews={reviews}>
            <Grid container spacing={2} sx={{ maxWidth: '1200px', mx: 'auto', pl: { lg: 2, md: 2, sm: 1, xs: 1 }, pr: { lg: 4, md: 4, sm: 5, xs: 5 } }}>
                <Stack px={2}>
                    <Typography fontWeight={600} color={colors.primary}>{'Prekių pirkimo – pardavimo internetinėje parduotuvėje opklinika.lt taisyklės'}</Typography>
                    <Typography color={colors.dark}>

                        <b> 1. Bendrosios nuostatos</b> <br />
                        1.1. Šios prekių pirkimo – pardavimo taisyklės (toliau „Taisyklės“), jas akceptavus Pirkėjui (susipažinus su Taisyklėmis bei pažymėjus varnelę prie teiginio „Susipažinau su opklinika.lt taisyklėmis ir su jomis sutinku“), yra šalims privalomas teisinis dokumentas, kuriame nustatomos Pirkėjo ir Pardavėjo teisės bei pareigos, prekių įsigijimo bei apmokėjimo už jas sąlygos, prekių pristatymo ir grąžinimo tvarka, šalių atsakomybė bei kitos su prekių pirkimu – pardavimu opklinika.lt internetinėje parduotuvėje susijusios nuostatos.<br />
                        1.2. Pardavėjas pasilieka teisę bet kuriuo metu pakeisti, taisyti ar papildyti Taisykles, atsižvelgdamas į teisės aktų nustatytus reikalavimus. Apie bet kokius pakeitimus, taisymus ar papildymus prisiregistravęs Pirkėjas bus informuojamas prisijungimo opklinika.lt puslapyje metu ir, norėdamas apsipirkti šioje internetinėje parduotuvėje, privalės iš naujo akceptuoti modifikuotas Taisykles.<br />
                        1.3. Internetinės parduotuvės opklinika.lt prekyba vykdoma tik Lietuvos Respublikos teritorijoje.<br />
                        1.4. Pirkti mūsų elektroninėje parduotuvėje turi teisę:<br />
                        1.4.1. veiksnūs fiziniai asmenys, t.y. asmenys, sulaukę pilnametystės, kurių veiksnumas nėra apribotas teismo tvarka;<br />
                        1.4.2. nepilnamečiai nuo keturiolikos iki aštuoniolikos metų amžiaus, tik turėdami tėvų arba rūpintojų sutikimą, išskyrus tuos atvejus, kai jie savarankiškai disponuoja savo pajamomis;<br />
                        1.4.3. juridiniai asmenys;<br />
                        1.4.4. visų aukščiau nurodytų asmenų įgalioti atstovai.<br />
                        1.5. Pirkėjas, akceptuodamas Taisykles, patvirtina, kad, remiantis Taisyklių 1.4. punktu, jis turi teisę pirkti prekes „opklinika.lt“ internetinėje parduotuvėje.<br />
                        1.6. Pirkėjas, patvirtindamas Taisykles, patvirtina, kad sutinka, jog jo užsakytos (-ų) prekės (-ių) instrukcija (-jos) lietuvių kalba, Pardavėjo nuožiūra ir esant techninėms galimybėms, gali būti pateikiama (-mos) tik Taisyklių 2.2. punkte numatyta tvarka Pirkėjo nurodytu elektroninio pašto adresu, išsiunčiant Pirkėjui aktyvią nuorodą į šią informaciją užsakytos (-ų) prekės (-ių) paruošimo metu.<br />
                        <b>2. Asmens duomenų apsauga<br /></b>
                        2.1. Užsisakyti prekes internetinėje parduotuvėje opklinika.lt Pirkėjas gali dviem būdais:<br />
                        2.1.1. užsiregistruodamas šioje internetinėje svetainėje, įvedant savo registracijos vardą ir slaptažodį;<br />
                        2.1.2. nesiregistruodamas šioje internetinėje svetainėje.<br />
                        2.2. Pirkėjas užsakydamas prekes tiek 2.1.1. tiek 2.1.2. Taisyklių punktuose numatytais būdais, atitinkamuose Pardavėjo pateikiamuose informacijos laukuose turi nurodyti prekių užsakymo tinkamam įvykdymui būtinus savo asmens duomenis: vardą, pavardę, prekių pristatymo adresą, telefono numerį ir elektroninio pašto adresą bei gali nurodyti savo lytį ir amžių.<br />
                        2.3. Pirkėjas patvirtindamas šias Taisykles sutinka, jog 2.2. punkte nurodyti jo asmens duomenys būtų tvarkomi prekių ir paslaugų pardavimo elektroninėje parduotuvėje opklinika.lt, Pardavėjo veiklos analizės ir tiesioginės rinkodaros tikslais bei sutinka, kad jo asmens duomenys – vardas, pavardė, prekių pristatymo adresas, telefono numeris ir elektroninio pašto adresas būtų atskleisti Pardavėjo partneriams (duomenų tvarkytojams), teikiantiems prekių pristatymo ar kitas su Pirkėjo užsakymo tinkamu įvykdymu susijusias paslaugas.<br />
                        2.4. Pirkėjas, sutikdamas, kad jo asmens duomenys būtų tvarkomi prekių ir paslaugų pardavimo Pardavėjo elektroninėje parduotuvėje tikslu, taip pat sutinka, kad jo nurodytais elektroninio pašto adresu ir telefono numeriu būtų siunčiami informaciniai pranešimai, kurie būtini prekių užsakymui įvykdyti.<br />
                        2.5. Pirkėjas, nepageidaujantis, kad jo elektroninio pašto adresas būtų tvarkomas tiesioginės rinkodaros tikslu, turi įeiti į skilties „Mano opklinika.lt “ skyrių „Mano duomenys“, nuimti varnelę prie teiginio „Naujienos el. paštu“ ir paspausti nuorodą „Atnaujinti“. Pirkėjas, nepageidaujantis, kad jo telefono numeris būtų tvarkomas tiesioginės rinkodaros tikslu, turi informuoti apie tai Pardavėją Taisyklių 2.1.1. punkte numatyta tvarka.<br />
                        2.6. Pardavėjas patvirtina, jog Pirkėjo nurodyti asmens duomenys bus tvarkomi tik prekių ir paslaugų pardavimo elektroninėje parduotuvėje opklinika.lt, Pardavėjo veiklos analizės ir tiesioginės rinkodaros (išskyrus atvejus, kai Pirkėjas Taisyklių 2.5 punkte nurodyta tvarka praneša, kad nepageidauja, jog jo asmens duomenys būtų tvarkomi tiesioginės rinkodaros tikslu) tikslais. Pardavėjas įsipareigoja neatskleisti Pirkėjo asmens duomenų tretiesiems asmenims, išskyrus Pardavėjo partnerius, teikiančius prekių pristatymo ar kitas, su Pirkėjo užsakymo tinkamu įvykdymu susijusias paslaugas. Visais kitais atvejais Pirkėjo asmens duomenys tretiesiems asmenims gali būti atskleidžiami tik LR teisės aktų numatyta tvarka.<br />
                        2.7. Pirkėjas kaip duomenų subjektas turi šias teises:<br />
                        2.7.1.  gauti iš Pardavėjo informaciją apie savo asmens duomenų tvarkymą, t.y. susipažinti su savo asmens duomenimis ir kaip jie yra tvarkomi, gauti informaciją, iš kokių šaltinių ir kokie jo asmens duomenys surinkti, kokiu tikslu jie tvarkomi, kokiems duomenų gavėjams teikiami ir buvo teikti bent per paskutinius 1 (vienerius) metus;<br />
                        2.7.2. reikalauti ištaisyti, sunaikinti savo asmens duomenis arba sustabdyti, išskyrus saugojimą, savo asmens duomenų tvarkymo veiksmus, kai duomenys tvarkomi nesilaikant Asmens duomenų teisinės apsaugos įstatymo ir kitų įstatymų nuostatų;<br />
                        2.7.3. nesutikti, kad būtų tvarkomi jo asmens duomenys.<br />
                        2.8. Remiantis Taisyklių 9.3.3. ir 9.4.3. punktais, Pardavėjo ar Lietuvos pašto darbuotojui pateiktas Pirkėjo asmens tapatybę patvirtinantis dokumentas ir jame esantys Pirkėjo duomenys naudojami tik tinkamam asmens tapatybės identifikavimui.<br />
                        2.9. Pirkėjas, pageidaujantis užsakyti Pardavėjo internetinėje parduotuvėje siūlomas partnerių paslaugas, gali tai padaryti išreikšdamas sutikimą, kad aiškiai nurodyti jo asmens duomenys būtų perduodami atitinkamam partneriui (duomenų gavėjui) užsakomų paslaugų suteikimo tikslu.<br />
                        2.10. Siekiant, kad Pirkėjui būtų suteiktos pilnavertės internetinės parduotuvės opklinika.lt paslaugos, Pirkėjo kompiuteryje (įrenginyje) Pardavėjas įrašo informaciją - slapukus. Įrašytą informaciją Pardavėjas naudoja Pirkėjo kaip ankstesnio opklinika.lt internetinės parduotuvės lankytojo atpažinimui, informacijos apie pirkinius, įdėtus į Pirkėjo prekių krepšelį, išsaugojimui, svetainės lankomumo statistikos rinkimui. Pirkėjas turi galimybę peržiūrėti, kokią informaciją (slapukus) Pardavėjas įrašo, ir gali ištrinti dalį ar visus įrašytus slapukus. Pirkėjas taip pat turi teisę nesutikti, kad būtų įrašoma ir naudojama informacija (slapukai) jo kompiuteryje (įrenginyje), tačiau tokiu atveju tam tikros internetinės parduotuvės opklinika.lt funkcijos jam gali būti neprieinamos. Pirkėjas, akceptuodamas Taisykles, sutinka, kad jo kompiuteryje (įrenginyje) būtų įrašoma informacija. Šį sutikimą Pirkėjas gali bet kada atšaukti, pakeisdamas savo interneto naršyklės nustatymus ar kreipdamasis į Pardavėją internetinėje parduotuvėje opklinika.lt nurodytais kontaktais.<br />
                        2.11. Bet kokį prašymą ar  nurodymą, susijusį su asmens duomenų tvarkymu, Pirkėjas turi pateikti Pardavėjui raštu vienu iš šių būdų: įteikdamas tokį prašymą ar nurodymą Pardavėjui tiesiogiai adresu Laisvės pr. 77, LT-06122 Vilnius, išsiųsdamas tokį prašymą ar nurodymą paštu šiame Taisyklių punkte nurodytu adresu ar elektroniniu paštu adresu info@opklinika.lt iš Taisyklių 2.2. punkte nurodyto elektroninio pašto adreso. Pardavėjas, gavęs tokį Pirkėjo prašymą ar nurodymą, ne vėliau kaip per 30 (trisdešimt) kalendorinių dienų pateiks Pirkėjui raštišką atsakymą .<br />
                        2.12. Pirkėjui nesutinkant su šiame Taisyklių skyriuje nurodytomis Asmens duomenų apsaugos nuostatomis, Pirkėjas praranda teisę naudotis internetinės parduotuvės opklinika.lt teikiamomis paslaugomis.<br />
                        <b> 3. Pirkimo – pardavimo sutarties sudarymo momentas<br /></b>
                        3.1. Sutartis tarp Pirkėjo ir Pardavėjo laikoma sudaryta nuo to momento, kai Pirkėjas, išsirinkęs perkamą (as) prekę (es) ir suformavęs prekių krepšelį, paspaudžia nuorodą „Apmokėti“.<br />
                        3.2. Kiekviena tarp Pirkėjo ir Pardavėjo sudaryta pirkimo – pardavimo sutartis yra registruojama ir saugoma opklinika.lt internetinės parduotuvės duomenų bazėje.<br />
                        <b>4. Pirkėjo teisės<br /></b>
                        4.1. Pirkėjas turi teisę pirkti prekes opklinika.lt internetinėje parduotuvėje šių Taisyklių ir kitose Pardavėjo internetinės parduotuvės informacijos skiltyse nustatyta tvarka.<br />
                        4.2. Pirkėjas turi teisę atsisakyti prekių pirkimo – pardavimo sutarties, sudarytos su opklinika.lt internetine parduotuve, pranešdamas apie tai Pardavėjui raštu (elektroniniu paštu, nurodant pageidaujamą grąžinti prekę ir jos užsakymo numerį) ne vėliau kaip per 7 (septynias) darbo dienas nuo daikto pristatymo/ atsiėmimo dienos, išskyrus atvejus, kai sutartis sudaryta dėl:<br />
                        4.2.1. prekių, kurios buvo gaminamos pagal Pirkėjo individualų užsakymą arba yra akivaizdžiai jam pritaikytos, arba kurios dėl savo prigimties po jų pateikimo Pirkėjui nebegali būti grąžintos dėl prekinių savybių praradimo (netekimo), yra greitai gendančios arba baigiasi jų galiojimo laikas.<br />
                        4.3. Taisyklių 4.2. punkte numatyta Pirkėjo teisė įgyvendinama vadovaujantis ūkio ministro 2001 m. rugpjūčio 17 d. įsakymu Nr. 258 patvirtintomis „Daiktų pardavimo ir paslaugų teikimo, kai sutartys sudaromos naudojant ryšio priemones, taisyklėmis“.<br />
                        4.4. Taisyklių 4.2 punkte numatyta teise Pirkėjas gali pasinaudoti tik tuo atveju, jeigu prekė nebuvo sugadinta arba iš esmės nepasikeitė jos išvaizda, taip pat ji nebuvo naudojama.<br />
                        4.5. Tuo atveju, kai Pirkėjas opklinika.lt internetinėje parduotuvėje įsigyja prekių komplektą ir vadovaudamasis Taisyklių 4.2. punkte numatyta teise pageidauja atsisakyti pirkimo-pardavimo sutarties tam tikros (tam tikrų) prekės (prekių) atžvilgiu, jis privalo grąžinti Pardavėjui visą prekių komplektą, t.y. Pirkėjas tokiu atveju gali pasinaudoti Taisyklių 4.2. punkte numatyta teise tik visų komplekte esančių prekių atžvilgiu. Tuo atveju, kai bent viena iš komplekte esančių prekių neatitinka Taisyklių 11.4 punkte numatytų reikalavimų, Pardavėjas turi teisę atsisakyti priimti grąžinamą prekių komplektą.<br />
                        <b> 5. Pirkėjo įsipareigojimai<br /></b>
                        5.1. Pirkėjas privalo sumokėti už prekes ir priimti jas šių Taisyklių nustatyta tvarka.<br />
                        5.2. Užsiregistravęs Pirkėjas įsipareigoja neperduoti tretiesiems asmenims savo prisijungimo duomenų. Jei Pirkėjas praranda prisijungimo duomenis, jis privalo nedelsiant informuoti apie tai Pardavėją skyriuje „Kontaktai“ nurodytomis susisiekimo priemonėmis.<br />
                        5.3. Jeigu pasikeičia užsiregistravusio Pirkėjo registracijos formoje pateikti duomenys, jis privalo nedelsdamas juos atnaujinti.<br />
                        5.4. Pirkėjas, naudodamasis opklinika.lt internetine parduotuve, įsipareigoja laikytis šių Taisyklių, kitų sąlygų, aiškiai nurodytų internetinėje parduotuvėje, bei nepažeisti Lietuvos Respublikos teisės aktų.<br />
                        <b> 6. Pardavėjo teisės<br /></b>
                        6.1. Pardavėjas turi teisę savo nuožiūra nustatyti minimalų prekių krepšelio dydį, t.y. minimalią sumą, kurią pasiekus bus vykdomas Pirkėjo užsakymas. Šios sumos dydis matomas peržiūrint prekių krepšelį.<br />
                        6.2. Jei Pirkėjas bando pakenkti internetinės parduotuvės darbo stabilumui ir saugumui ar pažeidžia savo įsipareigojimus, Pardavėjas turi teisę nedelsiant ir be perspėjimo apriboti ar sustabdyti jam galimybę naudotis internetine parduotuve arba išskirtiniais atvejais panaikinti Pirkėjo registraciją.<br />
                        6.3. Susidarius svarbioms aplinkybėms, Pardavėjas gali laikinai arba iš viso nutraukti internetinės parduotuvės veiklą, apie tai iš anksto nepranešę Pirkėjui.<br />
                        6.4. Pardavėjas turi teisę iš anksto nepranešęs Pirkėjui anuliuoti jo užsakymą, jeigu Pirkėjas, pasirinkęs Taisyklių 8.2.1. ar 8.2.2. punktuose numatytus apmokėjimo būdus, nesumoka už prekes per 3 (tris) darbo dienas.<br />
                        6.5. Kai Pirkėjas pasirenka Taisyklių 8.2.4. punkte numatytą apmokėjimo būdą – grynaisiais pinigais prekių pateikimo metu, Pardavėjas, iškilus neaiškumams dėl užsakyme pateiktos informacijos, susisiekia su Pirkėju užsakyme nurodytu telefonu. Prekių pristatymo terminas tokiu atveju pradedamas skaičiuoti nuo susisiekimo su Pirkėju dienos. Pardavėjas turi teisę iš anksto nepranešęs Pirkėjui anuliuoti jo užsakymą, jei Pardavėjui nepavyksta susisiekti su Pirkėju per 3 (tris) darbo dienas.<br />
                        <b>7. Pardavėjo įsipareigojimai</b> <br />
                        7.1. Pardavėjas įsipareigoja šiose Taisyklėse ir internetinėje parduotuvėje nustatytomis sąlygomis sudaryti Pirkėjui galimybę naudotis internetinės parduotuvės opklinika.lt teikiamomis paslaugomis.
                        7.2. Pardavėjas įsipareigoja gerbti Pirkėjo privatumo teisę į jam priklausančią asmeninę informaciją, t.y. Pirkėjo nurodytus asmens duomenis tvarkyti tik Taisyklių 2 skyriuje ir Lietuvos Respublikos teisės aktų nustatyta tvarka.
                        7.3. Pardavėjas įsipareigoja pristatyti Pirkėjo užsakytas prekes jo nurodytu adresu 9 Taisyklių skyriuje nurodytomis sąlygomis.
                        7.4. Pardavėjas, dėl svarbių aplinkybių negalėdamas pristatyti Pirkėjui užsakytos prekės, įsipareigoja pasiūlyti analogišką ar kiek įmanoma savo savybėmis panašesnę prekę. Pirkėjui atsisakius priimti analogišką ar savo savybėmis panašiausią prekę, Pardavėjas įsipareigoja grąžinti Pirkėjui sumokėtus pinigus per 3 (tris) darbo dienas, jeigu buvo atliktas išankstinis apmokėjimas.
                        7.5. Pirkėjui pasinaudojus Taisyklių 4.2. punkte numatyta teise ir esant Taisyklių 4.4. punkte numatytai sąlygai, Pardavėjas įsipareigoja grąžinti Pirkėjui sumokėtus pinigus per 10 (dešimt) darbo dienų, skaičiuojamų nuo grąžinamos prekės gavimo dienos. <br />
                        <b> 8. Prekių kainos, apmokėjimo tvarka ir terminai</b> <br />
                        8.1. Prekių kainos internetinėje parduotuvėje ir suformuotame užsakyme nurodomos litais su PVM.
                        8.2. Pirkėjas atsiskaito už prekes vienu iš šių būdų:
                        8.2.1. Apmokėjimas naudojantis elektronine bankininkyste – tai išankstinis apmokėjimas pasinaudojant Pirkėjo naudojama elektroninės bankininkystės sistema. Pirkėjas, norėdamas pasinaudoti šia apmokėjimo forma, turi būti pasirašęs elektroninės bankininkystės sutartį su vienu iš žemiau nurodytų bankų: AB bankas „Swedbank“, AB „DNB bankas“, AB „SEB bankas“, AB „Citadele bankas“, „Danske Bank A/S Lietuvos filialas“, AB „Nordea bankas“ bei AB „Šiaulių bankas“. Mokant už prekes šiuo būdu, Pirkėjui elektroninės bankininkystės sistemoje sugeneruojamas mokėjimas pagal jo apmokamą užsakymą. Pinigus Pirkėjas perveda į atitinkamame jo pasirinktame banke esančią „ opklinika.lt “ internetinės parduotuvės sąskaitą. Atsakomybė už duomenų saugumą šiuo atveju tenka atitinkamam bankui, kadangi visos piniginės operacijos vyksta banko elektroninės bankininkystės sistemoje.
                        8.2.2. Apmokėjimas banko pavedimu – tai išankstinis apmokėjimas, kai Pirkėjas, atsispausdinęs užsakymą ir nuėjęs į artimiausią banko skyrių, perveda pinigus į opklinika.lt banko sąskaitą.
                        8.2.3. Apmokėjimas grynaisiais pinigais prekių pristatymo/atsiėmimo metu – Pirkėjas už prekes sumoka jų pristatymo/atsiėmimo (perdavimo – priėmimo) metu.
                        8.3. Atsiskaitydamas 8.2.1., 8.2.2. ir 8.2.3. punktuose numatytais apmokėjimo būdais, Pirkėjas įsipareigoja sumokėti nedelsiant. Minėtaisiais atvejais, atsižvelgiant į Taisyklių 6.4. punkte numatytą Pardavėjo teisę, tik gavus apmokėjimą už prekes pradedamas formuoti prekių siuntinys ir pradedamas skaičiuoti prekių pristatymo terminas.
                        8.4. Pirkėjas, patvirtindamas Taisykles, sutinka, kad prekių pirkimo dokumentai – PVM sąskaitos faktūros, kurios kartu yra ir prekių garantiniai talonai, jam būtų pateikiamos elektroniniu būdu Pirkėjo registracijos formoje nurodytu elektroninio pašto adresu. Pardavėjas Pirkėjo pirktų prekių PVM sąskaitas faktūras taip pat patalpina opklinika.lt skiltyje „Mano paskyra“. PVM sąskaitos faktūros aukščiau nurodyta forma pateikiamos Pirkėjui ne vėliau kaip iki prekių perdavimo jam momento. Pirkėjui pateikus užsakymą, skiltyje „Mano paskyra“ jis mato ir gali atsispausdinti užsakymo lapą – išankstinio apmokėjimo sąskaitą. Sąskaitose nurodomos pasirinktos prekės, jų kiekis, suteikiamos nuolaidos, galutinė prekių kaina, įskaitant visus mokesčius, pristatymo mokesčiai, administravimo mokestis, nurodytas Taisyklių 8.6. punkte, ir kiti remiantis buhalterinę apskaitą reglamentuojančiais teisės aktais būtini pateikti duomenys.
                        8.5. Pirkėjas ir Pardavėjas susitaria, kad Pirkėjui pateikus prekės užsakymą ir Pardavėjui jį patvirtinus, prekės kaina gali pakisti, atsižvelgiant į prekės kainai įtakos turinčius objektyvius rodiklius, tokius kaip prekės savikainos padidėjimas, informacinių sistemų techninė klaida, papildomos su prekės pardavimu Pirkėjui susijusios išlaidos (LR CK 6.313 str. 7 d.). Pirkėjui tokiu atveju nesutinkant įsigyti prekę nauja kaina, bet kuri iš Šalių, įspėjusi apie tai kitą Šalį, turi teisę nutraukti prekės pirkimo-pardavimo sutartį. Šalys susitaria, kad nuostoliai, susiję su pirkimo-pardavimo sutarties nutraukimu šiame punkte numatyta tvarka, neatlyginami. <br />
                        <b>9. Prekių pristatymas</b> <br />
                        9.1. Pirkėjas, užsakydamas prekes, gali pasirinkti prekių pateikimo būdą, t.y. pasinaudoti Pardavėjo teikiama prekių pristatymo paslauga arba atsiimti prekes viename iš Lietuvos pašto skyrių ar Pardavėjo prekių atsiėmimo punkte.
                        9.2. Prekių pristatymas Pirkėjui:
                        9.2.1. Pirkėjas, užsakymo metu pasirinkęs prekių pristatymo paslaugą, įsipareigoja nurodyti tikslią prekių pristatymo vietą.
                        9.2.2. Pirkėjas įsipareigoja prekes priimti pats. Tuo atveju, kai jis prekių pats priimti negali, o prekės pristatytos nurodytu adresu ir remiantis kitais Pirkėjo pateiktais duomenimis, Pirkėjas neturi teisės reikšti Pardavėjui pretenzijų dėl prekių pristatymo netinkamam subjektui.
                        9.2.3. Prekes pristato Pardavėjas arba jo įgaliotas atstovas.
                        9.2.4. Prekių pristatymo (transportavimo) mokestis skaičiuojamas atsižvelgiant į prekių pristatymo vietą ir prekių svorį bei į tai, ar Pirkėjas pageidauja pasinaudoti prekių užnešimo paslauga:

                        9.3. Prekių atsiėmimas viename iš Lietuvos pašto skyrių:
                        9.3.1. Pirkėjas gali atsiimti prekes viename iš Lietuvos pašto skyrių, sumokėdamas 5,00 Lt mokestį.
                        9.3.2. Užsakytas prekes būtina atsiimti ne vėliau kaip per 3 (tris) darbo dienas, skaičiuojamas nuo Pardavėjo patvirtinimo, kad užsakymas jau yra Lietuvos pašto skyriuje ir jį galima atsiimti.
                        9.3.3. Prekes gali atsiimti ne tik užsakyme nurodytas gavėjas bet ir užsakymo pateikmo metu nurodytas kitas asmuo. Atsiimant prekes, būtina su savimi turėti ir Lietuvos pašto darbuotojui pateikti galiojantį asmens tapatybę patvirtinantį dokumentą (asmens tapatybės kortelę, pasą ar naujo pavyzdžio vairuotojo pažymėjimą).
                        9.3.4. Tuo atveju, kai užsakomos(-ų) prekės (-ių) svoris yra didesnis negu 20 kg, prekių atsiėmimo iš Lietuvos pašto skyrių paslauga neteikiama.
                        9.4. Prekių atsiėmimas Pardavėjo prekių atsiėmimo punktuose:
                        9.4.1. Pirkėjas gali atsiimti prekes nemokamai viename iš Pardavėjo prekių atsiėmimo punktų, esančių adresu Laisvės pr. 77, Vilnius.
                        9.4.2. Užsakytas prekes būtina atsiimti ne vėliau kaip per 3 (tris) darbo dienas, skaičiuojamas nuo Pardavėjo patvirtinimo, kad užsakymas jau paruoštas, gavimo momento.
                        9.4.3. Prekes gali atsiimti tik užsakymą pateikęs asmuo arba asmuo, nurodytas užsakymo pateikimo metu. Atsiimant prekes, būtina su savimi turėti ir Pardavėjo darbuotojui pateikti galiojantį asmens tapatybę patvirtinantį dokumentą (asmens tapatybės kortelę, pasą ar naujo pavyzdžio vairuotojo pažymėjimą).
                        9.5. Pardavėjas pateikia prekes Pirkėjui vadovaudamasis prekių aprašymuose nurodytais terminais. Šie terminai yra preliminarūs, be to netaikomi tais atvejais, kai Pardavėjo sandėlyje nėra reikiamų prekių, o Pirkėjas informuojamas apie jo užsakytų prekių trūkumą. Kartu Pirkėjas sutinka, jog išimtiniais atvejais prekių pateikimas gali vėluoti dėl nenumatytų, nuo Pardavėjo nepriklausančių aplinkybių. Tokiu atveju Pardavėjas įsipareigoja nedelsiant susisiekti su Pirkėju ir suderinti prekių pateikimo sąlygas.
                        9.6. Visais atvejais Pardavėjas atleidžiamas nuo atsakomybės už prekių pateikimo terminų pažeidimą, jeigu prekės Pirkėjui nėra pateikiamos arba pateikiamos ne laiku dėl Pirkėjo kaltės arba dėl nuo Pirkėjo priklausančių aplinkybių.
                        9.7. Prekių pateikimo Pirkėjui metu Pirkėjas privalo kartu su Pardavėju arba jo įgaliotu atstovu patikrinti siuntos ir prekės (-ių) būklę bei pasirašyti siuntos perdavimo – priėmimo dokumentą. Pirkėjui pasirašius siuntos perdavimo – priėmimo dokumente, laikoma, kad siunta yra perduota tinkamos būklės, prekių pažeidimų, kurių atsiradimo pagrindas priskirtinas ne gamykliniam brokui, bei prekės (-ių) komplektacijos neatitikimų (tokių, kuriuos galima nustatyti išorinės prekių apžiūros metu) nėra. Pastebėjęs, kad pateiktos siuntos pakuotė pažeista (suglamžyta, šlapia ar kitaip išoriškai pažeista), prekė(-ės) yra pažeista (-os) ir/ar prekė (-ės) yra netinkamos komplektacijos, Pirkėjas privalo tai pažymėti siuntos perdavimo – priėmimo dokumente bei, dalyvaujant Pardavėjui ar jo atstovui, surašyti laisvos formos siuntos ir/ar prekės (-ių) pažeidimo/neatitikimų aktą. Pirkėjui neatlikus šių veiksmų, Pardavėjas yra atleidžiamas nuo atsakomybės prieš Pirkėją dėl prekių pažeidimų, jeigu tokių pažeidimų atsiradimo pagrindas nėra gamyklinis brokas bei dėl prekių komplektacijos neatitikimų, jeigu šiuos neatitikimus galima nustatyti išorinės prekių apžiūros metu.
                        9.8. Detalesnė informacija, susijusi su prekių pristatymu, pateikiama skyriuje „Pristatymo sąlygos“.
                        10. Prekių kokybės garantija ir tinkamumo naudoti terminas
                        10.1. Kiekvienos opklinika.lt parduodamos prekės savybės bendrai nurodomos prie kiekvienos prekės esančiame prekės aprašyme.
                        10.2. Pardavėjas neatsako už tai, kad internetinėje parduotuvėje esančios prekės savo spalva, forma ar kitais parametrais gali neatitikti realaus prekių dydžio, formų ir spalvos dėl Pirkėjo naudojamo vaizduoklio ypatybių.
                        10.3. Pardavėjas tam tikroms prekių rūšims suteikia tam tikrą laiką galiojančią daiktų kokybės garantiją, kurios konkretus terminas ir kitos sąlygos nurodomi tokių prekių aprašymuose.
                        10.4. Pardavėjo teikiama kokybės garantija neapriboja ir nevaržo vartotojų teisių, kurias įsigijus netinkamos kokybės prekę ar paslaugą, jiems nustato teisės aktai.
                        10.5. Pardavėjas neteikia prekių garantinės priežiūros paslaugų, kiekvienu konkrečiu atveju nukreipdamas Pirkėją į garantinį aptarnavimą suteikiantį centrą.
                        10.6. Informacijai, esančiai informacijos nešikliuose, garantija netaikoma. Išlaidos dėl duomenų praradimo ar atstatymo nepadengiamos.
                        10.7. Tais atvejais, kai remiantis teisės aktais konkrečių prekių atžvilgiu nustatomas tam tikras tinkamumo naudoti terminas, Pardavėjas įsipareigoja tokias prekes parduoti Pirkėjui taip, kad jam būtų suteikta reali galimybė tokiomis prekėmis pasinaudoti iki tinkamumo naudoti termino pabaigos.
                        10.8. Detalesnė informacija, susijusi su prekių garantinėmis sąlygomis, pateikiama internetinės parduotuvės skyriuje„Garantiniai įsipareigojimai“.
                        11. Prekių grąžinimas ir keitimas
                        11.1. Parduotų prekių trūkumai šalinami, nekokybiškos prekėsi keičiamos, grąžinamos vadovaujantis ūkio ministro 2001m. birželio 29 d. įsakymu Nr. 217 „Dėl Daiktų grąžinimo ir keitimo taisyklių patvirtinimo“ patvirtintomis Daiktų grąžinimo ir keitimo taisyklėmis.
                        11.2. Norėdamas grąžinti prekę(es) 11.1. Taisyklių punkte nurodytais atvejais, Pirkėjas turi užpildyti prekių grąžinimo dokumentą, kuris yra pridedamas Pirkėjui prie jo užsakytų prekių, ir pateikti jį kartu su grąžinama preke(ėmis).
                        11.3. 11.1. Taisyklių punkte numatyta teise Pirkėjas gali pasinaudoti per 7 (septynias) darbo dienas nuo prekių pristatymo jam dienos, informuodamas apie tai Pardavėją 4.2. Taisyklių punkte numatyta tvarka.
                        11.4. Pirkėjui grąžinant prekes, būtina laikytis šių sąlygų:
                        11.4.1. grąžinama prekė turi būti originalioje tvarkingoje pakuotėje (šis punktas netaikomas tuo atveju, kai grąžinama nekokybiška prekė);
                        11.4.2. prekė turi būti Pirkėjo nesugadinta;
                        11.4.3. prekė turi būti nenaudota, nepraradusi prekinės išvaizdos (nepažeistos etiketės, nenuplėštos apsauginės plėvelės ir kt.) (šis punktas netaikomas tuo atveju, kai grąžinama nekokybiška prekė);
                        11.4.4. grąžinama prekė turi būti tos pačios komplektacijos, kokios buvo Pirkėjo gauta;
                        11.4.5. grąžinant prekę būtina pateikti jos įsigijimo dokumentą, garantinį taloną (jei jis buvo išduotas) ir užpildytą 11.2.Taisyklių punkte nurodytą grąžinimo dokumentą.
                        11.5. Pardavėjas turi teisę nepriimti Pirkėjo grąžinamų prekių, jei Pirkėjas nesilaiko šiame straipsnyje nustatytos prekių grąžinimo tvarkos.
                        11.6. Grąžinamas prekes Pirkėjas gali pristatyti pats adresu Laisvės pr. 77, Vilnius darbo dienomis nuo 09.00 iki 17.00 valandos, arba atsiųsti naudojantis savo pasirinkto kurjerio paslaugomis. Tuo atveju, kai prekė grąžinama remiantis 4.2. punkte numatyta teise, Pirkėjui tenka prekių grąžinimo išlaidos. Kai grąžinama gauta ne ta prekė ir/ar nekokybiška prekė, Pardavėjas įsipareigoja pasiimti tokias prekes ir jas pakeisti analogiškomis tinkamomis prekėmis. Tuo atveju, kai Pardavėjas neturi analogiškų prekių, jis grąžina Pirkėjui už prekę(-es) sumokėtus pinigus.
                        11.7. Prekių grąžinimas ir keitimas vykdomas vadovaujantis ūkio ministro 2001 m. birželio 29 d. įsakymu Nr. 217 patvirtintomis „Daiktų grąžinimo ir keitimo taisyklėmis“ bei ūkio ministro 2001 m. rugpjūčio 17 d. įsakymu Nr. 258 patvirtintomis „Daiktų pardavimo ir paslaugų teikimo, kai sutartys sudaromos naudojant ryšio priemones, taisyklėmis“.
                        11.8. Pinigai už grąžintas prekes visais atvejais pervedami mokėjimo pavedimu ir tik į mokėtojo banko sąskaitą.
                        12. Atsakomybė
                        12.1. Pirkėjas yra visiškai atsakingas už jo pateikiamų asmens duomenų teisingumą. Jei Pirkėjas nepateikia tikslių asmens duomenų, Pardavėjas neatsako už dėl to atsiradusius padarinius ir įgyja teisę reikalauti iš Pirkėjo patirtų tiesioginių nuostolių atlyginimo.
                        12.2. Pirkėjas atsako už veiksmus, atliktus naudojantis šia internetine parduotuve.
                        12.3. Užsiregistravęs Pirkėjas atsako už savo prisijungimo duomenų perdavimą tretiesiems asmenims. Jei opklinika.lt teikiamomis paslaugomis naudojasi trečiasis asmuo, prisijungęs prie internetinės parduotuvės naudodamasis Pirkėjo prisijungimo duomenimis, Pardavėjas šį asmenį laiko Pirkėju.
                        12.4. Pardavėjas atleidžiamas nuo bet kokios atsakomybės tais atvejais, kai nuostoliai kyla dėl to, jog Pirkėjas, neatsižvelgdamas į Pardavėjo rekomendacijas ir savo įsipareigojimus, nesusipažino su šiomis Taisyklėmis, nors tokia galimybė jam buvo suteikta.
                        12.5. Jei Pardavėjo internetinėje parduotuvėje yra nuorodos į kitų įmonių, įstaigų, organizacijų ar asmenų tinklapius, Pardavėjas nėra atsakingas už ten esančią informaciją ar vykdomą veiklą, tų tinklapių neprižiūri, nekontroliuoja ir toms įmonėms bei asmenims neatstovauja.
                        12.6. Pardavėjas neatsako dėl Pirkėjo ir Pardavėjo partnerių, kurių paslaugas Pirkėjas užsako, tinkamo tarpusavio įsipareigojimų vykdymo.
                        12.7. Atsiradus žalai, kaltoji šalis atlygina kitai šaliai tiesioginius nuostolius.
                        13. Pardavėjo taikomos rinkodaros priemonės
                        13.1. Pardavėjas savo nuožiūra gali inicijuoti internetinėje parduotuvėje opklinika.lt įvairias akcijas.
                        13.4. Pardavėjas turi teisę vienašališkai, be atskiro įspėjimo, pakeisti akcijų sąlygas, taip pat jas panaikinti, be to, vienašališkai, be atskiro įspėjimo. Bet kokie akcijų sąlygų, gavimo ir panaudojimo atsiskaitant už prekes tvarkos pakeitimai ar panaikinimas galioja tik į priekį, t.y. nuo jų atlikimo momento.
                        14. Apsikeitimas informacija
                        14.1. Pardavėjas visus pranešimus siunčia Taisyklių 2.2. punkte numatyta tvarka Pirkėjo pateiktu elektroninio pašto adresu.
                        14.2. Pirkėjas visus pranešimus ir klausimus siunčia Pardavėjo internetinės parduotuvės skyriuje „Kontaktai“ nurodytomis susisiekimo priemonėmis.
                        15. Baigiamosios nuostatos
                        15.1. Šios taisyklės sudarytos vadovaujantis LR teisės aktais.
                        15.2. Šių taisyklių pagrindu kylantiems santykiams taikoma LR teisė.
                        15.3. Visi nesutarimai, kilę dėl šių taisyklių vykdymo, sprendžiami derybų būdu. Nepavykus susitarti, ginčai sprendžiami LR įstatymų nustatyta tvarka.

                    </Typography>
                </Stack>
            </Grid>
        </Layout>
    )
}

export default PrivacyPolicyPagePage